import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/client/header";
import Provider from "@/util/provider";
import Footer from "@/components/client/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vu.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="static">
        <Provider>
          <Header />
          {children}
        </Provider>
        <div className="fixed p-4 bottom-0 left-0">
          <Footer />
        </div>
      </body>
    </html>
  );
}
